/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_unb_cic_tdp_base_GPUSorter */

#ifndef _Included_br_unb_cic_tdp_base_GPUSorter
#define _Included_br_unb_cic_tdp_base_GPUSorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_unb_cic_tdp_base_GPUSorter
 * Method:    sort
 * Signature: ([S[S[SDI)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_br_unb_cic_tdp_base_GPUSorter_sort
  (JNIEnv *, jclass, jshortArray, jshortArray, jshortArray, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
